Added wordpress components
aws-samples/amazon-ec2-image-builder-samples pull request #31
Opened 2022-04-11 09:26 UTC by guysqr

*Issue #, if available:*

*Description of changes:*
I added components that can install WordPress in various ways.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-04-15 05:21 UTC, austoonz requested changes
Thank you for these submissions!

I have added a few comments, primarily around removing statements of design or implementation recommendations, or suggestions that may indicate usage of these samples outside of testing and learning purposes (which is the intention of artifacts in this repository). Instead, for these additions, we should direct customers to our official best practices blog or whitepaper for WordPress on AWS, or to the reference architecture for deploying WordPress on AWS.

Additionally, we may need to include a license summary file, similar to the [one provided](https://github.com/aws-samples/aws-refarch-wordpress#license-summary) in the reference architecture repository. I will need to sync with internal teams about this prior to merging this pull request.

I have not yet performed a proper review of the component contents, I still need to review those. I will most likely clone this and test the components to validate the end state (given we have no automated testing to do that in this repository)

2022-04-15 05:21 UTC, austoonz commented on Components/Linux/wordpress-recipes-linux/README.md
> +Note that there is no SSL configured on the AMI. We recommend offloading SSL to a ALB and deploying your certificate to that ALB using AWS Certificate Manager (ACM).
We should not be making service, design or implementation recommendations in this samples repository.

Instead, perhaps move these statements to the top of the readme so they're more obvious, and leave the statements as what isn't being done, and that these samples are not intended for production use.

---

NOTE: These samples are not intended for production use and are provided to demonstrate how WordPress could be installed using EC2 Image Builder. These samples do not implement the best practices guidance for deploying WordPress on AWS (such as ensuring SSL is configured).

2022-04-15 05:21 UTC, austoonz commented on Components/Linux/wordpress-recipes-linux/README.md
> +1. Assumes php 7.4 is/will be pre-installed (eg from the Amazon-managed `php-7-4-linux` ImageBuilder component)
I think we should make a statement about the underlying Operating System these are designed for. I am presuming that would be Amazon Linux 2, but we should state this as the samples (using `yum`) clearly won't work on other platforms such as Ubuntu. (I'm not saying we need to make them work elsewhere, just to state what the samples are intended to work on)

2022-04-15 05:21 UTC, austoonz commented on Components/Linux/wordpress-recipes-linux/install_wordpress.yml
> +description: this document installs Wordpress on Amazon Linux
`This document installs WordPress on Amazon Linux 2` (nits for correct casing and the correct OS)

2022-04-15 05:21 UTC, austoonz commented on Components/Linux/wordpress-recipes-linux/install_wordpress_with_db.yml
> +description: this document installs Wordpress with Db on Amazon Linux
Similar to above, `This document installs WordPress with a database on Amazon Linux 2`

2022-04-15 05:21 UTC, austoonz commented on Components/Linux/wordpress-recipes-linux/install_wordpress_with_db_pma.yml
> +description: this document installs Wordpress with Db on Amazon Linux
`This document installs WordPress with a database and phpMyAdmin on Amazon Linux 2`

2022-04-15 05:21 UTC, austoonz commented on Components/Linux/wordpress-recipes-linux/README.md
> +We suggest if you spin up new WordPress instances regularly that you schedule the ImageBuilder pipeline to regularly rebuild the AMI so it does not drift too far from the most recent version.
Perhaps remove `We suggest` and just make this `If you spin up...`.

`We suggest` (IMO) indicates that we're suggesting to continue using these samples for a non-learning type purpose, which is not the intention of these samples (given we have the best practices and reference architecture guides for WordPress on AWS).

2022-04-18 08:26 UTC, guysqr commented
Thanks for those pointers. I will incorporate your suggestions.

2022-04-20 04:02 UTC, guysqr commented
It's ready for another review

2022-05-09 16:37 UTC, austoonz requested changes
I have reviewed internally and there is no need for additional licensing statements. 

Once the license file and the reference to it included in this PR are removed I'll go ahead and merge.

Thank you!

2022-05-28 23:34 UTC, guysqr commented
> I have reviewed internally and there is no need for additional licensing statements.
> 
> Once the license file and the reference to it included in this PR are removed I'll go ahead and merge.
> 
> Thank you!

Hi @austoonz - updates made as per your request. Removed license file and block from readme.

2022-05-29 06:24 UTC, merged